services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: iurii
      POSTGRES_PASSWORD: q
      POSTGRES_DB: iurii
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npx prisma db push && node server.js"

volumes:
  pgdata:
