services:
  db:
    image: postgres:15-alpine
    container_name: shared-db-container
    restart: always
    network_mode: "host" # Контейнер использует порты сервера напрямую
    environment:
      POSTGRES_USER: iurii
      POSTGRES_PASSWORD: q
      POSTGRES_DB: iurii
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: ghcr.io/i-3/nextjs-app:latest
    restart: always
    network_mode: "host" # Теперь Next.js доступен на порту 3000 сервера
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://iurii:q@127.0.0.1:5432/iurii
    command: >
      sh -c " until PGPASSWORD=q psql -h 127.0.0.1 -U iurii -d postgres -c 'SELECT 1' > /dev/null 2>&1; do sleep 1; done; PGPASSWORD=q psql -h 127.0.0.1 -U iurii -d postgres -c 'ALTER USER iurii WITH CREATEDB;' > /dev/null 2>&1 || true; PGPASSWORD=q psql -h 127.0.0.1 -U iurii -d postgres -c 'CREATE DATABASE directus;' > /dev/null 2>&1 || true; PGPASSWORD=q psql -h 127.0.0.1 -U iurii -d iurii -c 'CREATE TABLE IF NOT EXISTS applications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), employer TEXT, vacancy TEXT, state TEXT, date DATE);'; node server.js "

volumes:
  pgdata:
